print(f'=-='*30)
print('SUPERMERCADO GOOGLE')
print(f'=-='*30)
arroz = ('ARROZ','------------------','R$',15)
feijao = ('FEIJÃO','------------------','R$',17.50)
trembolona = ('TREMBOLONA','------------------','R$',120.50)
gh = ('GH','------------------','R$',1200)
creatina = ('CREATINA','------------------','R$',130)
supercoffe = ('SUPERCOFFE','------------------','R$',129.99)
print(arroz)
print(feijao)
print(trembolona)
print(gh)
print(creatina)
print(supercoffe)
